### PR TITLE
corrected some spelling mistakes

### PR DESCRIPTION
**Pull request by bertolo1988**
I am a native portuguese speaker and i found this 2 little spelling mistakes.
If you want more help, let me know!

Best regards.

### CODE REVIEW

**Comment by una** [comment]
Ahh thanks! Do you still want this PR merged? You can resolve those with `git pull --rebase upstream master`

**Comment by bertolo1988** [comment]
Merge please.

**Comment by una** [comment]
Can you fix the merge conflicts first, please? 😄

**Comment by bertolo1988** [comment]
I used a recursive search and found a few more!

**Comment by bertolo1988** [comment]
I am not experienced using github, but i think that you can now safely accept my pull request!

**Comment by una** [comment]
nice job! :)

**Comment by bertolo1988** [comment]
Thanks alot! Keep up!

**Pull request merged**
